version: '3.8'

services:
  # CloudAMQP Alternative - Local RabbitMQ
  rabbitmq:
    image: rabbitmq:3.12-management-alpine
    container_name: brandpillar-rabbitmq-local
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: brandpillar
      RABBITMQ_DEFAULT_PASS: secret
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis Cloud Alternative - Local Redis
  redis:
    image: redis:7-alpine
    container_name: brandpillar-redis-local
    ports:
      - "6380:6379"
    command: redis-server --appendonly yes --requirepass secret
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  rabbitmq_data:
  redis_data:
