# Railway Configuration for Personal Brand DNA
[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

# Services configuration
[[services]]
name = "frontend"
source = "frontend/"
startCommand = "npm start"

[[services]]
name = "backend"
source = "backend/"
startCommand = "npm start"

[[services]]
name = "ai-pipeline"
source = "ai-pipeline/"
startCommand = "uvicorn main:app --host 0.0.0.0 --port $PORT"

# Database configuration (Railway PostgreSQL)
[plugins.postgresql]
enabled = true

[plugins.redis]
enabled = true