import { WorkshopState } from '../store/slices/workshopSlice';
import { ArchetypeScore } from './archetypeService';
import { ContentPillarAnalysis } from './contentPillarService';
import { UVPAnalysis } from './uvpConstructorService';
import { 
  cleanTextForPDF, 
  createPDFFilename, 
  formatPDFDate,
  getArchetypeColor 
} from '../utils/pdfHelpers';

// Brand colors
const brandColors = {
  primary: '#2563eb', // Blue-600
  secondary: '#7c3aed', // Purple-600
  accent: '#10b981', // Green-500
  dark: '#111827', // Gray-900
  gray: '#6b7280', // Gray-500
  lightGray: '#f3f4f6', // Gray-100
  white: '#ffffff'
};

// Typography styles
const styles = {
  header: {
    fontSize: 32,
    bold: true,
    color: brandColors.dark,
    margin: [0, 0, 0, 20] as [number, number, number, number]
  },
  subheader: {
    fontSize: 24,
    bold: true,
    color: brandColors.dark,
    margin: [0, 20, 0, 10] as [number, number, number, number]
  },
  sectionTitle: {
    fontSize: 18,
    bold: true,
    color: brandColors.primary,
    margin: [0, 20, 0, 10] as [number, number, number, number]
  },
  body: {
    fontSize: 11,
    lineHeight: 1.4,
    color: brandColors.dark,
    margin: [0, 5, 0, 5] as [number, number, number, number]
  },
  subtitle: {
    fontSize: 14,
    bold: true,
    color: brandColors.gray,
    margin: [0, 10, 0, 5] as [number, number, number, number]
  },
  quote: {
    fontSize: 13,
    italics: true,
    color: brandColors.gray,
    margin: [20, 10, 20, 10] as [number, number, number, number]
  }
};

export interface BrandHouseReportData {
  workshopState: WorkshopState;
  archetypeResult: {
    primary: ArchetypeScore;
    secondary?: ArchetypeScore;
    hybrid?: {
      name: string;
      description: string;
      ratio: number;
    };
  };
  mission: string;
  contentPillars: ContentPillarAnalysis;
  uvpAnalysis: UVPAnalysis;
  actionableContent?: {
    headlines: Array<{
      style: string;
      headline: string;
      keywords: string[];
      characterCount: number;
    }>;
    pitches: Array<{
      type: string;
      pitch: string;
      wordCount: number;
      keyPoints: string[];
    }>;
    contentIdeas: string[];
  };
}

/**
 * Lazy-loaded PDF generation function
 * Only loads pdfMake when actually needed
 */
export const generateBrandHousePDF = async (data: BrandHouseReportData): Promise<void> => {
  try {
    // Dynamically import pdfMake only when needed
    const [
      { default: pdfMake },
      { default: pdfFonts }
    ] = await Promise.all([
      import('pdfmake/build/pdfmake'),
      import('pdfmake/build/vfs_fonts')
    ]);

    // Register fonts
    pdfMake.vfs = pdfFonts.pdfMake.vfs;

    const {
      workshopState,
      archetypeResult,
      mission,
      contentPillars,
      uvpAnalysis,
      actionableContent
    } = data;

    const { primary, secondary, hybrid } = archetypeResult;
    const archetype = primary.archetype;

    // Create document definition
    const docDefinition = {
      info: {
        title: 'BrandPillar AI - Personal Brand House Report',
        author: 'BrandPillar AI',
        subject: `Brand Analysis for ${workshopState.values.slice(0, 2).join(' & ')} Professional`,
        keywords: 'personal brand, brand strategy, professional development',
        creator: 'BrandPillar AI Platform',
        producer: 'BrandPillar AI'
      },
      pageSize: 'A4',
      pageMargins: [60, 80, 60, 60] as [number, number, number, number],
      
      header: {
        margin: [60, 20, 60, 0] as [number, number, number, number],
        table: {
          widths: ['*', 'auto'],
          body: [
            [
              { text: 'Personal Brand House Report', style: 'subtitle', border: [false, false, false, false] },
              { text: formatPDFDate(), style: 'body', alignment: 'right', border: [false, false, false, false] }
            ]
          ]
        }
      },

      footer: (currentPage: number, pageCount: number) => ({
        margin: [60, 10, 60, 10] as [number, number, number, number],
        table: {
          widths: ['*', 'auto'],
          body: [
            [
              { text: 'Generated by BrandPillar AI', style: 'body', color: brandColors.gray, border: [false, false, false, false] },
              { text: `Page ${currentPage} of ${pageCount}`, style: 'body', color: brandColors.gray, alignment: 'right', border: [false, false, false, false] }
            ]
          ]
        }
      }),

      content: [
        // Cover section
        {
          alignment: 'center',
          margin: [0, 0, 0, 40] as [number, number, number, number],
          stack: [
            { text: 'Your Personal Brand House', style: 'header' },
            { text: `You are ${archetype.name.toLowerCase().startsWith('a') || archetype.name.toLowerCase().startsWith('e') || archetype.name.toLowerCase().startsWith('i') || archetype.name.toLowerCase().startsWith('o') || archetype.name.toLowerCase().startsWith('u') ? 'an' : 'a'} ${archetype.name}`, style: 'subheader', color: getArchetypeColor(archetype.name) },
            { text: cleanTextForPDF(archetype.description), style: 'quote', margin: [40, 20, 40, 20] as [number, number, number, number] },
            { text: `Confidence Score: ${Math.round(primary.confidence * 100)}%`, style: 'subtitle', margin: [0, 20, 0, 0] as [number, number, number, number] }
          ]
        },

        { text: '', pageBreak: 'after' },

        // Executive Summary
        { text: 'Executive Summary', style: 'sectionTitle' },
        {
          text: [
            'This Brand House report provides a comprehensive analysis of your professional brand based on your values, communication style, audience focus, and personality traits. ',
            `As ${archetype.name.toLowerCase().startsWith('a') || archetype.name.toLowerCase().startsWith('e') || archetype.name.toLowerCase().startsWith('i') || archetype.name.toLowerCase().startsWith('o') || archetype.name.toLowerCase().startsWith('u') ? 'an' : 'a'} ${archetype.name}, you have a unique opportunity to leverage your strengths for professional growth and influence.`
          ],
          style: 'body'
        },

        // Core Values
        { text: 'Your Core Values', style: 'sectionTitle' },
        {
          ul: workshopState.values.map(value => cleanTextForPDF(value)),
          style: 'body'
        },

        // Mission Statement
        { text: 'Your Mission Statement', style: 'sectionTitle' },
        { text: cleanTextForPDF(mission), style: 'quote' },

        // Unique Value Proposition
        { text: 'Your Unique Value Proposition', style: 'sectionTitle' },
        { text: cleanTextForPDF(uvpAnalysis.uvpVariations[0].uvp), style: 'body' },
        
        // Key Differentiators
        { text: 'Key Differentiators', style: 'subtitle' },
        {
          ul: uvpAnalysis.uniqueFactors.slice(0, 5).map(factor => cleanTextForPDF(factor)),
          style: 'body'
        },

        { text: '', pageBreak: 'after' },

        // Content Strategy
        { text: 'Your Content Strategy', style: 'sectionTitle' },
        { text: 'Based on your brand analysis, here are your three content pillars:', style: 'body' },

        // Content Pillars
        ...contentPillars.pillars.map(pillar => ([
          { text: `${pillar.name} (${pillar.weight}%)`, style: 'subtitle' },
          { text: cleanTextForPDF(pillar.description), style: 'body' },
          {
            text: 'Topics to focus on:',
            style: 'body',
            margin: [0, 5, 0, 2] as [number, number, number, number]
          },
          {
            ul: pillar.topics.slice(0, 3).map(topic => cleanTextForPDF(topic)),
            style: 'body',
            margin: [0, 0, 0, 10] as [number, number, number, number]
          }
        ])).flat(),

        // Actionable Content (if available)
        ...(actionableContent ? [
          { text: '', pageBreak: 'after' },
          { text: 'Ready-to-Use Content', style: 'sectionTitle' },
          
          // LinkedIn Headlines
          { text: 'LinkedIn Headlines', style: 'subtitle' },
          {
            ol: actionableContent.headlines.slice(0, 3).map(headline => 
              `${cleanTextForPDF(headline.headline)} (${headline.characterCount} characters)`
            ),
            style: 'body'
          },

          // Elevator Pitches
          { text: 'Elevator Pitches', style: 'subtitle' },
          {
            ol: actionableContent.pitches.slice(0, 2).map(pitch => 
              `${pitch.type}: ${cleanTextForPDF(pitch.pitch.substring(0, 200))}...`
            ),
            style: 'body'
          },

          // Content Ideas
          { text: 'Content Ideas', style: 'subtitle' },
          {
            ol: actionableContent.contentIdeas.slice(0, 5).map(idea => cleanTextForPDF(idea)),
            style: 'body'
          }
        ] : []),

        { text: '', pageBreak: 'after' },

        // Action Plan
        { text: 'Your 30-Day Action Plan', style: 'sectionTitle' },
        {
          ol: [
            'Update your LinkedIn headline using one of the provided options',
            'Write and publish 2-3 posts per week focusing on your content pillars',
            'Practice your elevator pitch and use it in networking situations',
            'Share your expertise through comments and engagement with others\' content',
            'Monitor your brand consistency across all professional platforms'
          ],
          style: 'body'
        },

        // Next Steps
        { text: 'Recommended Next Steps', style: 'subtitle' },
        {
          ul: [
            'Set up news monitoring for your industry to stay current with trends',
            'Create a content calendar based on your three pillars',
            'Join or start conversations in your area of expertise',
            'Measure your engagement and adjust your strategy accordingly',
            'Consider creating longer-form content like articles or videos'
          ],
          style: 'body'
        },

        // Footer
        {
          margin: [0, 40, 0, 0] as [number, number, number, number],
          stack: [
            { text: 'Thank you for using BrandPillar AI', style: 'subtitle', alignment: 'center' },
            { text: 'Continue building your authentic professional brand.', style: 'body', alignment: 'center' },
            { text: 'https://brandpillar-ai.vercel.app', style: 'body', alignment: 'center', color: brandColors.primary }
          ]
        }
      ],

      styles: styles,

      defaultStyle: {
        font: 'Roboto'
      }
    };

    // Generate and download PDF
    const filename = createPDFFilename(archetype.name);
    pdfMake.createPdf(docDefinition).download(filename);

  } catch (error) {
    console.error('Error generating PDF:', error);
    throw new Error('Failed to generate PDF report. Please try again.');
  }
};

export default generateBrandHousePDF;