import pdfMake from 'pdfmake/build/pdfmake';
import pdfFonts from 'pdfmake/build/vfs_fonts';
import { TDocumentDefinitions, Content, ContentColumns, ContentTable } from 'pdfmake/interfaces';
import { WorkshopState } from '../store/slices/workshopSlice';
import { ArchetypeScore } from './archetypeService';
import { ContentPillarAnalysis } from './contentPillarService';
import { UVPAnalysis } from './uvpConstructorService';
import { 
  cleanTextForPDF, 
  createPDFFilename, 
  formatPDFDate,
  getArchetypeColor 
} from '../utils/pdfHelpers';

// Register fonts
pdfMake.vfs = pdfFonts.pdfMake.vfs;

// Brand colors
const brandColors = {
  primary: '#2563eb', // Blue-600
  secondary: '#7c3aed', // Purple-600
  accent: '#10b981', // Green-500
  dark: '#111827', // Gray-900
  gray: '#6b7280', // Gray-500
  lightGray: '#f3f4f6', // Gray-100
  white: '#ffffff'
};

// Typography styles
const styles = {
  header: {
    fontSize: 32,
    bold: true,
    color: brandColors.dark,
    margin: [0, 0, 0, 20] as [number, number, number, number]
  },
  subheader: {
    fontSize: 24,
    bold: true,
    color: brandColors.dark,
    margin: [0, 20, 0, 10] as [number, number, number, number]
  },
  sectionTitle: {
    fontSize: 18,
    bold: true,
    color: brandColors.primary,
    margin: [0, 20, 0, 10] as [number, number, number, number]
  },
  body: {
    fontSize: 11,
    color: brandColors.dark,
    lineHeight: 1.6
  },
  quote: {
    fontSize: 14,
    italics: true,
    color: brandColors.gray,
    margin: [20, 10, 20, 10] as [number, number, number, number]
  },
  caption: {
    fontSize: 9,
    color: brandColors.gray,
    margin: [0, 5, 0, 5] as [number, number, number, number]
  }
};

export interface BrandHouseReportData {
  workshopState: WorkshopState;
  archetypeResult: {
    primary: ArchetypeScore;
    secondary?: ArchetypeScore;
    hybrid?: {
      name: string;
      description: string;
      ratio: number;
    };
  };
  mission: string;
  contentPillars: ContentPillarAnalysis;
  uvpAnalysis: UVPAnalysis;
  starterContent: string[];
}

export async function generateBrandHousePDF(data: BrandHouseReportData): Promise<void> {
  const { workshopState, archetypeResult, mission, contentPillars, uvpAnalysis, starterContent } = data;
  
  // Helper function to create a colored box
  const coloredBox = (content: Content, bgColor: string): Content => ({
    table: {
      widths: ['*'],
      body: [[content]]
    },
    layout: {
      fillColor: () => bgColor,
      hLineWidth: () => 0,
      vLineWidth: () => 0,
      paddingLeft: () => 15,
      paddingRight: () => 15,
      paddingTop: () => 15,
      paddingBottom: () => 15
    }
  });

  // Helper function to create a progress bar
  const progressBar = (value: number, label: string): Content => ({
    columns: [
      { text: label, width: 100, style: 'caption' },
      {
        canvas: [
          {
            type: 'rect',
            x: 0,
            y: 0,
            w: 150,
            h: 8,
            r: 4,
            color: brandColors.lightGray
          },
          {
            type: 'rect',
            x: 0,
            y: 0,
            w: 150 * value,
            h: 8,
            r: 4,
            color: brandColors.primary
          }
        ]
      },
      { text: `${Math.round(value * 100)}%`, width: 40, style: 'caption', alignment: 'right' }
    ],
    margin: [0, 5, 0, 5] as [number, number, number, number]
  });

  const documentDefinition: TDocumentDefinitions = {
    pageSize: 'A4',
    pageMargins: [40, 60, 40, 60],
    
    // Header and footer
    header: (currentPage: number, pageCount: number) => {
      if (currentPage === 1) return null;
      return {
        columns: [
          { text: 'Brand House Report', style: 'caption', margin: [40, 20, 0, 0] },
          { text: `Page ${currentPage} of ${pageCount}`, style: 'caption', alignment: 'right', margin: [0, 20, 40, 0] }
        ]
      };
    },
    
    footer: (currentPage: number) => {
      if (currentPage === 1) return null;
      return {
        text: 'Generated by BrandPillar AI • Confidential',
        style: 'caption',
        alignment: 'center',
        margin: [0, 0, 0, 20] as [number, number, number, number]
      };
    },
    
    content: [
      // Cover Page
      {
        text: 'Your Brand House',
        style: 'header',
        alignment: 'center',
        margin: [0, 100, 0, 20] as [number, number, number, number]
      },
      {
        text: 'Personal Brand Framework & Strategy Guide',
        fontSize: 16,
        color: brandColors.gray,
        alignment: 'center',
        margin: [0, 0, 0, 40] as [number, number, number, number]
      },
      
      // Archetype Badge
      coloredBox({
        columns: [
          {
            width: '*',
            stack: [
              {
                text: archetypeResult.hybrid ? archetypeResult.hybrid.name : archetypeResult.primary.archetype.name,
                fontSize: 20,
                bold: true,
                color: brandColors.white,
                alignment: 'center'
              },
              {
                text: archetypeResult.hybrid ? archetypeResult.hybrid.description : archetypeResult.primary.archetype.description,
                fontSize: 12,
                color: brandColors.white,
                alignment: 'center',
                margin: [0, 10, 0, 0] as [number, number, number, number]
              }
            ]
          }
        ]
      }, brandColors.primary),
      
      // Date and confidence
      {
        columns: [
          {
            text: `Generated on ${formatPDFDate()}`,
            style: 'caption'
          },
          {
            text: `${Math.round(archetypeResult.primary.confidence * 100)}% Confidence Score`,
            style: 'caption',
            alignment: 'right'
          }
        ],
        margin: [0, 20, 0, 0] as [number, number, number, number]
      },
      
      // Page break after cover
      { text: '', pageBreak: 'after' },
      
      // Executive Summary
      { text: 'Executive Summary', style: 'subheader' },
      {
        text: [
          'This Brand House report provides a comprehensive analysis of your personal brand based on your workshop responses. ',
          'Your unique combination of values, communication style, and expertise has been analyzed using AI to create a personalized brand framework.'
        ],
        style: 'body',
        margin: [0, 0, 0, 20] as [number, number, number, number]
      },
      
      // Key Findings Box
      coloredBox({
        stack: [
          { text: 'Key Findings', fontSize: 14, bold: true, color: brandColors.dark, margin: [0, 0, 0, 10] as [number, number, number, number] },
          {
            ul: [
              `Primary Archetype: ${archetypeResult.primary.archetype.name}`,
              `Core Values: ${workshopState.values.selected.slice(0, 3).join(', ')}`,
              `Target Audience: ${workshopState.audiencePersonas[0]?.name || 'Professional audience'}`,
              `Content Strategy: ${contentPillars.pillars.map(p => `${p.name} (${p.percentage}%)`).join(', ')}`
            ],
            style: 'body'
          }
        ]
      }, brandColors.lightGray),
      
      // Mission Statement
      { text: 'Your Mission Statement', style: 'sectionTitle' },
      {
        text: `"${cleanTextForPDF(mission)}"`,
        style: 'quote',
        alignment: 'center'
      },
      
      // Page break
      { text: '', pageBreak: 'after' },
      
      // Archetype Analysis
      { text: 'Archetype Analysis', style: 'subheader' },
      {
        text: 'Your brand archetype was determined through AI analysis of five key factors:',
        style: 'body',
        margin: [0, 0, 0, 20] as [number, number, number, number]
      },
      
      // Breakdown scores
      progressBar(archetypeResult.primary.breakdown.values, 'Values Alignment'),
      progressBar(archetypeResult.primary.breakdown.personality, 'Personality Match'),
      progressBar(archetypeResult.primary.breakdown.writing, 'Writing Style'),
      progressBar(archetypeResult.primary.breakdown.tone, 'Communication Tone'),
      progressBar(archetypeResult.primary.breakdown.audience, 'Audience Fit'),
      
      // Archetype details
      { text: 'Archetype Characteristics', style: 'sectionTitle' },
      {
        columns: [
          {
            stack: [
              { text: 'Core Traits', fontSize: 12, bold: true, margin: [0, 0, 0, 5] as [number, number, number, number] },
              {
                ul: archetypeResult.primary.archetype.personalityTraits.map(trait => 
                  trait.charAt(0).toUpperCase() + trait.slice(1)
                ),
                style: 'body'
              }
            ]
          },
          {
            stack: [
              { text: 'Keywords', fontSize: 12, bold: true, margin: [0, 0, 0, 5] as [number, number, number, number] },
              {
                ul: archetypeResult.primary.archetype.keywords.slice(0, 5).map(keyword => 
                  keyword.charAt(0).toUpperCase() + keyword.slice(1)
                ),
                style: 'body'
              }
            ]
          }
        ],
        columnGap: 20
      },
      
      // Page break
      { text: '', pageBreak: 'after' },
      
      // Values Foundation
      { text: 'Your Brand Foundation', style: 'subheader' },
      {
        text: 'Your values form the foundation of your brand house. They guide your decisions, content, and professional relationships.',
        style: 'body',
        margin: [0, 0, 0, 20] as [number, number, number, number]
      },
      
      // Values hierarchy
      { text: 'Values Hierarchy', style: 'sectionTitle' },
      {
        table: {
          widths: ['*', 100],
          body: [
            [
              { text: 'Value', bold: true, style: 'body' },
              { text: 'Type', bold: true, style: 'body' }
            ],
            ...workshopState.values.selected.map((value, index) => [
              { text: value.charAt(0).toUpperCase() + value.slice(1), style: 'body' },
              { 
                text: index < 2 ? 'Core (Non-negotiable)' : 
                      workshopState.values.aspirational?.includes(value) ? 'Aspirational' : 'Supporting',
                style: 'caption'
              }
            ])
          ]
        },
        layout: 'lightHorizontalLines'
      },
      
      // Value stories (if available)
      ...(Object.keys(workshopState.values.stories || {}).length > 0 ? [
        { text: 'Value Stories', style: 'sectionTitle' },
        ...Object.entries(workshopState.values.stories).map(([valueId, story]) => [
          { text: valueId.charAt(0).toUpperCase() + valueId.slice(1), fontSize: 12, bold: true, margin: [0, 10, 0, 5] as [number, number, number, number] },
          { text: story, style: 'body', margin: [0, 0, 0, 10] as [number, number, number, number] }
        ]).flat()
      ] : []),
      
      // Page break
      { text: '', pageBreak: 'after' },
      
      // Unique Value Proposition
      { text: 'Unique Value Proposition', style: 'subheader' },
      coloredBox({
        stack: [
          {
            text: uvpAnalysis.variations[0].fullStatement,
            fontSize: 14,
            color: brandColors.dark,
            lineHeight: 1.4
          },
          {
            text: '\nLinkedIn Headline:',
            fontSize: 10,
            bold: true,
            color: brandColors.gray,
            margin: [0, 10, 0, 5] as [number, number, number, number]
          },
          {
            text: uvpAnalysis.variations[0].linkedinHeadline,
            fontSize: 12,
            color: brandColors.primary
          }
        ]
      }, brandColors.lightGray),
      
      // Key Differentiators
      { text: 'Key Differentiators', style: 'sectionTitle' },
      {
        ul: uvpAnalysis.variations[0].differentiators,
        style: 'body'
      },
      
      // Market Position
      { text: 'Market Position', style: 'sectionTitle' },
      {
        text: uvpAnalysis.industryContext.competitiveLandscape,
        style: 'body'
      },
      
      // Page break
      { text: '', pageBreak: 'after' },
      
      // Content Strategy
      { text: 'Content Strategy', style: 'subheader' },
      {
        text: contentPillars.contentStrategy,
        style: 'body',
        margin: [0, 0, 0, 20] as [number, number, number, number]
      },
      
      // Content Pillars
      { text: 'Your Three Content Pillars', style: 'sectionTitle' },
      ...contentPillars.pillars.map(pillar => [
        coloredBox({
          columns: [
            {
              width: 60,
              text: `${pillar.percentage}%`,
              fontSize: 24,
              bold: true,
              color: brandColors.primary,
              alignment: 'center'
            },
            {
              width: '*',
              stack: [
                { text: pillar.name, fontSize: 16, bold: true, color: brandColors.dark },
                { text: pillar.description, style: 'body', margin: [0, 5, 0, 0] as [number, number, number, number] }
              ]
            }
          ]
        }, brandColors.white),
        {
          text: 'Topics to Cover:',
          fontSize: 10,
          bold: true,
          color: brandColors.gray,
          margin: [0, 10, 0, 5] as [number, number, number, number]
        },
        {
          ul: pillar.topics.slice(0, 5),
          style: 'body',
          margin: [0, 0, 0, 20] as [number, number, number, number]
        }
      ]).flat(),
      
      // Page break
      { text: '', pageBreak: 'after' },
      
      // Target Audience
      { text: 'Target Audience', style: 'subheader' },
      ...workshopState.audiencePersonas.map(persona => [
        coloredBox({
          stack: [
            { text: persona.name, fontSize: 16, bold: true, color: brandColors.dark },
            { text: `${persona.role} in ${persona.industry}`, style: 'body', margin: [0, 5, 0, 10] as [number, number, number, number] },
            {
              columns: [
                {
                  stack: [
                    { text: 'Pain Points', fontSize: 10, bold: true, margin: [0, 0, 0, 5] as [number, number, number, number] },
                    { ul: persona.painPoints.slice(0, 3), fontSize: 9 }
                  ]
                },
                {
                  stack: [
                    { text: 'Goals', fontSize: 10, bold: true, margin: [0, 0, 0, 5] as [number, number, number, number] },
                    { ul: persona.goals.slice(0, 3), fontSize: 9 }
                  ]
                }
              ]
            },
            ...(persona.transformation ? [
              {
                text: `Transformation: ${persona.transformation.outcome}`,
                fontSize: 10,
                italics: true,
                color: brandColors.primary,
                margin: [0, 10, 0, 0] as [number, number, number, number]
              }
            ] : [])
          ]
        }, brandColors.lightGray),
        { text: '', margin: [0, 10] as [number, number] }
      ]).flat(),
      
      // Page break
      { text: '', pageBreak: 'after' },
      
      // Communication Style
      { text: 'Communication Style', style: 'subheader' },
      {
        text: 'Your authentic voice profile based on tone preferences:',
        style: 'body',
        margin: [0, 0, 0, 20] as [number, number, number, number]
      },
      
      // Tone preferences visualization
      {
        table: {
          widths: [150, '*'],
          body: [
            ['Formality', progressBar((workshopState.tonePreferences.formal_casual + 50) / 100, '')],
            ['Detail Level', progressBar((workshopState.tonePreferences.concise_detailed + 50) / 100, '')],
            ['Creativity', progressBar((workshopState.tonePreferences.analytical_creative + 50) / 100, '')],
            ['Playfulness', progressBar((workshopState.tonePreferences.serious_playful + 50) / 100, '')],
          ]
        },
        layout: 'noBorders'
      },
      
      // Voice guidelines
      { text: 'Voice Guidelines', style: 'sectionTitle' },
      {
        text: contentPillars.voiceGuidelines,
        style: 'body'
      },
      
      // Page break
      { text: '', pageBreak: 'after' },
      
      // Content Ideas
      { text: 'Your First 15 Content Ideas', style: 'subheader' },
      {
        text: 'Ready-to-use content ideas aligned with your brand archetype and content pillars:',
        style: 'body',
        margin: [0, 0, 0, 20] as [number, number, number, number]
      },
      
      // Content ideas in a grid
      {
        columns: [
          {
            ol: starterContent.slice(0, 8).map(idea => ({ text: idea, style: 'body', margin: [0, 5] as [number, number] }))
          },
          {
            ol: starterContent.slice(8, 15).map(idea => ({ text: idea, style: 'body', margin: [0, 5] as [number, number] })),
            start: 9
          }
        ],
        columnGap: 20
      },
      
      // Page break
      { text: '', pageBreak: 'after' },
      
      // Action Plan
      { text: 'Your 30-Day Action Plan', style: 'subheader' },
      {
        text: 'Follow this step-by-step plan to activate your personal brand:',
        style: 'body',
        margin: [0, 0, 0, 20] as [number, number, number, number]
      },
      
      // Week 1
      coloredBox({
        stack: [
          { text: 'Week 1: Foundation', fontSize: 14, bold: true, color: brandColors.white },
          {
            ul: [
              'Update LinkedIn headline with your UVP',
              'Revise LinkedIn about section using your mission statement',
              'Create content calendar based on your three pillars',
              'Write and publish your first piece using content idea #1'
            ],
            color: brandColors.white,
            fontSize: 10
          }
        ]
      }, brandColors.primary),
      
      // Week 2
      coloredBox({
        stack: [
          { text: 'Week 2: Content Creation', fontSize: 14, bold: true, color: brandColors.white },
          {
            ul: [
              'Publish 3 posts using your starter content ideas',
              'Engage with 5 thought leaders in your industry',
              'Join 2 LinkedIn groups where your audience gathers',
              'Test different content formats (text, image, poll)'
            ],
            color: brandColors.white,
            fontSize: 10
          }
        ]
      }, brandColors.secondary),
      
      // Week 3
      coloredBox({
        stack: [
          { text: 'Week 3: Engagement', fontSize: 14, bold: true, color: brandColors.white },
          {
            ul: [
              'Respond to all comments on your posts',
              'Start conversations on others\' relevant posts',
              'Share insights from your expertise pillar',
              'Connect with 10 new people in your target audience'
            ],
            color: brandColors.white,
            fontSize: 10
          }
        ]
      }, brandColors.accent),
      
      // Week 4
      coloredBox({
        stack: [
          { text: 'Week 4: Optimization', fontSize: 14, bold: true, color: brandColors.dark },
          {
            ul: [
              'Analyze which content performed best',
              'Refine your content topics based on engagement',
              'Schedule regular content creation time',
              'Plan next month\'s content calendar'
            ],
            color: brandColors.dark,
            fontSize: 10
          }
        ]
      }, brandColors.lightGray),
      
      // Final CTA
      { text: '', margin: [0, 40] as [number, number] },
      {
        text: 'Ready to build your personal brand with AI-powered content?',
        fontSize: 16,
        bold: true,
        alignment: 'center',
        color: brandColors.primary
      },
      {
        text: 'Visit app.brandpillar.ai to start creating content that sounds like you.',
        style: 'body',
        alignment: 'center',
        margin: [0, 10] as [number, number]
      }
    ],
    
    // Document metadata
    info: {
      title: 'Brand House Report',
      author: 'BrandPillar AI',
      subject: 'Personal Brand Framework',
      keywords: 'personal brand, archetype, content strategy'
    },
    
    // Default styles
    defaultStyle: {
      font: 'Helvetica'
    }
  };

  // Generate and download the PDF with a proper filename
  const filename = createPDFFilename(
    archetypeResult.hybrid ? archetypeResult.hybrid.name : archetypeResult.primary.archetype.name
  );
  pdfMake.createPdf(documentDefinition).download(filename);
}

// Helper function to generate a preview of the PDF (first page only)
export async function generateBrandHousePreview(data: BrandHouseReportData): Promise<string> {
  // This would generate a base64 preview of the first page
  // For now, we'll return a placeholder
  return new Promise((resolve) => {
    // In a real implementation, you'd generate the PDF and extract the first page
    resolve('data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkYPhfDwAChwGA60e6kgAAAABJRU5ErkJggg==');
  });
}

// Export types for use in components
export type { BrandHouseReportData };