global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'agents'
    static_configs:
      - targets: ['host.docker.internal:3003']
        labels:
          service: 'ai-agents'
    metrics_path: '/metrics'

  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']
    metrics_path: '/metrics'

  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']

# Alerting rules
rule_files:
  - 'alerts/*.yml'

# Alert manager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: []  # Add alertmanager if needed